#!/bin/bash
if [[ "$UID" -ne 0 ]]; then
	sudo $0 $@
	exit
fi
RED='\033[1;31m'
GREEN='\033[1;32m'
BLUE='\033[1;34m'
NC='\033[0m'

############################################################################################################
source /opt/bpi-r2-router-builder/files/root/.bash_aliases

############################################################################################################
DEV=$(sudo blkid | grep "BPI-BOOT" | grep -v "/dev/loop" | cut -d":" -f 1 | head -1)
if [[ -z "${DEV}" ]]; then
	echo -e "${RED}ERROR:${NC} SD Card not detected with partition 1 label of ${BLUE}BPI-BOOT${NC}!"
	exit 1
elif [[ ! "${DEV}" =~ /dev/mmcblk* ]]; then 
	DEV=${DEV:0:8}
	SRCH=${DEV}2
	umount ${DEV}* >& /dev/null
else
	SRCH=${DEV/p1/p2}
	if [[ ! "$(mount | grep ${SRCH} | awk '{print $3}')" == "/ro" ]]; then
		echo -e "${RED}ERROR:${NC} Cannot backup root partition without overlay active.  Aborting!"
		exit 1
	elif [[ "$(mount | grep ${SRCH} | awk '{print $3" "$6}')" =~ rw ]]; then
		echo -e "${RED}ERROR:${NC} Root partition must be read-only in order to backup.  Aborting!"
		exit 1
	fi
	DEV=${DEV/p1/}
fi
END=$(( $(sudo fdisk --list ${DEV} | grep "${SRCH}" | awk '{print $3}') + 1 ))

############################################################################################################
FILE=${1:-"bpiwrt_v$(date +"%Y.%m%d.%H%M").img"}
MB=$(( ${END} / 2 / 1024 / 4))
SZ=$(( ${END} * 512 ))
echo -e "${GREEN}================================================================${NC}"
echo -e "${GREEN}NOTE:${NC} Backing up ${BLUE}${DEV}${NC} to ${BLUE}${FILE}${NC}...."
echo -e "${GREEN}INFO:${NC} $(printf "%'.0f\n" ${END}) blocks = $(printf "%'.0f\n" $(( ${MB} * 4 ))) MB ($(printf "%'.0f\n" ${SZ}))"
echo -e "${GREEN}================================================================${NC}"
dd if=${DEV} of=${FILE} bs=4M count=${MB} status=progress
if [[ ! "${DEV}" =~ "/dev/mmcblk" ]]; then
	echo -e "${GREEN}================================================================${NC}"
	eject ${DEV}
	echo -e "${GREEN}INFO:${NC} ${BLUE}${DEV}${NC} has been ejected!"
	$(dirname $0)/cleanup ${FILE} --origin=${DEV}
else
	scp ${FILE} doug@doug-pc.local:~/R2/
fi
