#!/bin/bash
if [[ "$UID" -ne 0 ]]; then
	sudo $0 $@
	exit
fi
RED='\033[1;31m'
GREEN='\033[1;32m'
BLUE='\033[1;34m'
NC='\033[0m'

los() {
	img="$1"
	dev="$(sudo losetup --show -f -P "$img")"
	echo "$dev"
	for part in "$dev"?*; do
		[ "$part" = "${dev}p*" ] && part="${dev}"
		dst="/mnt/$(basename "$part")"
		echo "$dst"
		sudo mkdir -p "$dst"
		sudo mount "$part" "$dst"
	done
}
losd() {
	for part in "${1}"?*; do
		if [ "${part}" = "${1}p*" ]; then
			part="${1}"
		fi
		dst="/mnt/$(basename "$part")"
		sudo umount "$dst"
		sudo rmdir "$dst"
	done
	sudo losetup -d "$1"
}

DEV=$(sudo blkid | grep "BPI-BOOT" | grep -v "/dev/loop" | cut -d":" -f 1 | head -1)
if [[ -z "${DEV}" ]]; then
	echo -e "${RED}ERROR:${NC} SD Card not detected with partition 1 label of ${BLUE}BPI-BOOT${NC}!"
	exit 1
elif [[ "${DEV}" =~ /dev/mmcblk* ]]; then 
	DEV=${DEV:0:12}
	SRCH=${DEV}p2
else 
	DEV=${DEV:0:8}
	SRCH=${DEV}2
fi
umount ${DEV}* >& /dev/null
END=$(( $(sudo fdisk --list ${DEV} | grep "${SRCH}" | awk '{print $3}') + 1 ))

FILE=${1:-"bpiwrt_v$(date +"%Y.%m%d.%H%M").img"}
MB=$(( ${END} / 2 / 1024 / 4))
SZ=$(( ${END} * 512 ))
echo -e "${GREEN}================================================================${NC}"
echo -e "${GREEN}NOTE:${NC} Backing up ${BLUE}${DEV}${NC} to ${BLUE}${FILE}${NC}...."
echo -e "${GREEN}INFO:${NC} $(printf "%'.0f\n" ${END}) blocks = $(printf "%'.0f\n" $(( ${MB} * 4 ))) MB ($(printf "%'.0f\n" ${SZ}))"
echo -e "${GREEN}================================================================${NC}"
dd if=${DEV} of=${FILE} bs=4M count=${MB} status=progress
echo -e "${GREEN}================================================================${NC}"
[[ ! "${DEV}" =~ "/dev/mmcblk" ]] && eject ${DEV}
echo -e "${GREEN}INFO:${NC} ${BLUE}${DEV}${NC} has been ejected!"
$(dirname $0)/cleanup ${FILE}
