#!/bin/bash
if [[ "$UID" -ne 0 ]]; then
	sudo $0 $@
	exit
fi
RED='\033[1;31m'
GREEN='\033[1;32m'
BLUE='\033[1;34m'
NC='\033[0m'

los() {
	img=$1
	dev="$(sudo losetup --show -f -P "$img")"
	dir=${dev/dev/mnt}
	mkdir -p $dir
	mount ${dev}p2 $dir
	mount ${dev}p1 $dir/boot
	echo $dir
}
losd() {
	dir=$1
	dev=${dir/mnt/dev}
	umount ${dev}*
	rmdir ${dir}
	losetup -d $dev
}

####################################################################################################
FILE="${1}"
if [[ -z "${FILE}" || ! -e "${FILE}" ]]; then
	# Assemble the list of files to display:
	count=0
	while read -r file
	do
		 options+=($((++count)) "$file")
	done <<< $(ls -r *.img*)

	# Display the dialog box:
	cmd=(dialog --keep-tite --menu "Select Image to Clean:" 22 76 16)
	CHOICE=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
	[[ "$CHOICE" -eq 0 ]] && exit 0
	FILE=${options[ $(( $CHOICE * 2 - 1)) ]}
fi
echo -e "${GREEN}================================================================${NC}"
echo -e "${GREEN}NOTE:${NC} Cleaning up ${BLUE}${FILE}${NC}...."

####################################################################################################
echo -e "${GREEN}================================================================${NC}"
echo -e "${GREEN}NOTE:${NC} Mounting partitions within the image..."
DEV=$(los ${FILE})

####################################################################################################
echo -e "${GREEN}NOTE:${NC} Extracting empty BPIWRT disk image..."
[[ "$(df /tmp | grep -v Filesystem | head -1 | awk '{print $4}')" -lt 2129921 ]] && DEST=./ || DEST=/tmp
cp $(dirname $(ls -l $0 | awk '{print $NF}'))/bpiwrt_empty.img.gz ${DEST}
gunzip -f ${DEST}/bpiwrt_empty.img.gz
OUT=$(los ${DEST}/bpiwrt_empty.img)

####################################################################################################
echo -e "${GREEN}NOTE:${NC} Cleaning up boot partition..."
rm ${DEV}/boot/bananapi/bpi-r2/linux/uImage >& /dev/null
rm ${DEV}/boot/*.conf >& /dev/null
DTB=${DEV}/boot/bananapi/bpi-r2/linux/dtb/bpi-r2.dtb
[[ -f ${DTB}.old ]] && mv ${DTB}.old ${DTB}

####################################################################################################
chroot ${DEV} $(dirname $0)/remove_files

####################################################################################################
echo -e "${GREEN}NOTE:${NC} Copy system files to empty image..."
cp -aR ${DEV}/* ${OUT}/

####################################################################################################
echo -e "${GREEN}NOTE:${NC} Unmount partitions from system..."
losd ${DEV}
losd ${OUT}
mv ${DEST}/bpiwrt_empty.img ${FILE}

####################################################################################################
echo -e "${GREEN}================================================================${NC}"
echo -e "${GREEN}NOTE:${NC} Compressing image..."
gzip -fkv ${FILE}
echo -e "${GREEN}================================================================${NC}"
echo -e "${GREEN}SUCCESS!${NC}  Image backup completed and prepped successfully!"
