#!/bin/bash
#############################################################################
# This script creates the python virtual environment for mitmproxy.
#############################################################################
# Create and activate virtual environment:
python3 -m venv /opt/mitmproxy/venv
source /opt/mitmproxy/venv/bin/activate

# Install the precompiled wheels:
python3 -m pip install --no-index --find-links=/tmp/wheels/mitmproxy mitmproxy
