#!/bin/bash
if [[ "$UID" -ne 0 ]]; then
	sudo $0 $@
	exit
fi
RED='\033[1;31m'
GREEN='\033[1;32m'
BLUE='\033[1;34m'
NC='\033[0m'

####################################################################################################
echo -e "${GREEN}NOTE:${NC} Clearing the local repository of retrieved package files..."
apt-get clean
apt-get autoclean
echo -e "${GREEN}NOTE:${NC} Purge unnecessary packages..."
apt-get -y purge --autoremove

####################################################################################################
if [[ -f /usr/local/bin/pihole ]]; then
	echo -e "${GREEN}NOTE:${NC} Clearing Pi-Hole history..."
	pihole -f
fi

####################################################################################################
echo -e "${GREEN}NOTE:${NC} Restoring original network configuration to root partition..."
DIR=/opt/bpi-r2-router-builder/files
for file in /etc/network/interfaces.d/* /etc/dnsmasq.d/[a-z]*.conf /etc/hostapd/*.conf; do
	if test -f ${DIR}${file}; then cp ${DIR}${file} $file; else rm $file; fi
done

####################################################################################################
echo -e "${GREEN}NOTE:${NC} Removing unnecessary files from root partition..."
rm -rf /tmp/* >& /dev/null
rm -rf /root/.config >& /dev/null
rm -rf /root/.local >& /dev/null
rm /etc/udev/rules.d/70-persistent-net.rules >& /dev/null
rm /root/.bash_history >& /dev/null
rm /root/.ssh/known_hosts >& /dev/null
rm /var/lib/vnstat/* >& /dev/null
rm /var/misc/* >& /dev/null
rm /var/cache/apt/*.bin >& /dev/null
rm /lib/modules/$(ls /lib/modules/)/{build,source} >& /dev/null
rm -r /var/log/*.{xz,gz,1,2} >& /dev/null
for file in $(find /var/log -type f | grep -v /var/log/apt/history.log); do echo -n > $file; done
cat /var/log/apt/history.log | tail -3 > /tmp/history.log
mv /tmp/history.log /var/log/apt/history.log
rm /var/lib/apt/lists/* >& /dev/null
rm /etc/samba/smb.d/router >& /dev/null
touch /var/lib/apt/lists/lock

####################################################################################################
echo -e "${GREEN}NOTE:${NC} Repulling BPIWRT builder repo to minimize size..."
GIT=($(whereis git | cut -d":" -f 2))
if [[ ! -z "${GIT[@]}" ]]; then
	mv /opt/bpi-r2-router-builder /opt/r2-backup && git clone --depth=1 https://github.com/xptsp/bpiwrt-builder /opt/bpi-r2-router-builder && rm -rf /opt/r2-backup
	chown pi:pi -R /opt/bpi-r2-router-builder/router
fi
