#!/bin/bash
if [[ "$UID" -ne 0 ]]; then
	sudo $0 $@
	exit
fi
RED='\033[1;31m'
GREEN='\033[1;32m'
BLUE='\033[1;34m'
NC='\033[0m'

####################################################################################################
echo -e "${GREEN}NOTE:${NC} Clearing the local repository of retrieved package files..."
apt-get clean
apt-get autoclean
echo -e "${GREEN}NOTE:${NC} Purge unnecessary packages..."
apt-get -y purge --autoremove

####################################################################################################
if [[ -f /usr/local/bin/pihole ]]; then
	echo -e "${GREEN}NOTE:${NC} Clearing Pi-Hole history..."
	pihole -f
fi

####################################################################################################
echo -e "${GREEN}NOTE:${NC} Restoring original network configuration to root partition..."
DIR=/opt/bpi-r2-router-builder/files
for file in /etc/network/interfaces.d/* /etc/dnsmasq.d/[a-z]*.conf /etc/hostapd/*.conf; do
	if test -f ${DIR}${file}; then cp ${DIR}${file} $file; else rm $file; fi
done

####################################################################################################
echo -e "${GREEN}NOTE:${NC} Removing unnecessary files from root partition..."
rm /etc/nftables-added.conf >& /dev/null
rm -rf /tmp/* >& /dev/null
rm -rf /root/.config >& /dev/null
rm -rf /root/.local >& /dev/null
rm /root/.bash_history >& /dev/null
rm /root/.ssh/known_hosts >& /dev/null
rm /var/lib/vnstat/* >& /dev/null
rm /var/misc/* >& /dev/null
rm /var/cache/apt/*.bin >& /dev/null
rm /lib/modules/$(ls /lib/modules/)/{build,source} >& /dev/null
rm -r /var/log/*.{xz,gz,1,2} >& /dev/null
for file in $(ls /var/log/samba | grep -v "log.[sn]mbd"); do rm $file >& /dev/null; done
for file in $(find /var/log -type f | grep -v /var/log/apt/history.log); do echo -n > $file; done
cat /var/log/apt/history.log | tail -4 > /tmp/history.log
mv /tmp/history.log /var/log/apt/history.log
rm /var/lib/apt/lists/* >& /dev/null
rm /etc/samba/smb.d/webui >& /dev/null
touch /var/lib/apt/lists/lock
echo "WEBUI_SHARE=n" > /boot/persistent.conf
rm /boot/bpiwrt.cfg >& /dev/null
cp /dev/null /var/lib/dhcp/dhclient.wan.leases
rm /etc/pihole/gravity_old.db >& /dev/null

####################################################################################################
GIT=($(whereis git | cut -d":" -f 2))
if [[ ! -z "${GIT[@]}" ]]; then
	echo -e "${GREEN}NOTE:${NC} Repulling SSD1306 Stats repo to minimize size..."
	rm -rf /opt/stats
	git clone --depth=1 https://github.com/xptsp/bpi-r2-ssd1306-display /opt/stats

	echo -e "${GREEN}NOTE:${NC} Repulling wireless-regdb repo to minimize size..."
	rm -rf /opt/wireless-regdb
	git clone --depth=1 https://git.kernel.org/pub/scm/linux/kernel/git/sforshee/wireless-regdb.git/ /opt/wireless-regdb

	echo -e "${GREEN}NOTE:${NC} Repulling multicast-relay repo to minimize size..."
	rm -rf /opt/multicast-relay
	git clone --depth=1 https://github.com/alsmith/multicast-relay /opt/multicast-relay
fi
