#!/bin/bash
export DEBIAN_FRONTEND=noninteractive
export LANG=C

##############################################################################################
# Execute second-stage of image building:
##############################################################################################
[[ -f /debootstrap/debootstrap ]] && /debootstrap/debootstrap --second-stage

##############################################################################################
# Install some packages that Frank-W had in his image:
##############################################################################################
apt install -y apt-transport-https bridge-utils dnsmasq hostapd ca-certificates openssh-server ppp pppoeconf pppoe

##############################################################################################
# Fix the hung SSH session issue with Debian Buster:
##############################################################################################
ln -sf /usr/share/doc/openssh-client/examples/ssh-session-cleanup.service /etc/systemd/system/
systemctl enable ssh-session-cleanup
systemctl start ssh-session-cleanup

##############################################################################################
# Install files from the GitHub repository:
##############################################################################################
/opt/bpi-r2-router-builder/upgrade.sh --force-copy
systemctl enable firewall

##############################################################################################
# Upgrade any packages needing upgrading:
##############################################################################################
apt update
apt upgrade -y
systemctl disable hostapd

##############################################################################################
# Install some necessary packages:
##############################################################################################
apt install -y locales wget git apt-transport-https toilet pmount eject lsb-release bash-completion dialog mosquitto-clients sudo

##############################################################################################
# Create our default users and assign default passwords to users:
##############################################################################################
# Assign default password to user "root":
echo -e "bananapi\nbananapi" | passwd -q root

# Create a user named "pi", being a member of the "sudo" and "users" group.
useradd -m -G sudo,users -s /bin/bash pi
echo -e "bananapi\nbananapi" | passwd -q pi

# Create a user name "vpn", being a member of the "users" and "pi" group:
useradd -m -G users -s /usr/sbin/nologin vpn
usermod -aG vpn pi

##############################################################################################
# Do some tasks necessary to make this image work correctly:
##############################################################################################
# Create necessary symlinks for a few commands:
ln -sf /usr/bin/clear /usr/local/bin/cls
ln -sf /opt/bpi-r2-router-builder/helpers/router-helper.sh /usr/local/bin/router-helper

# Set hostname:
echo "bpiwrt" > /etc/hostname
hostname bpiwrt

# Set IP address of both hostname and pi.hole
echo "192.168.2.1     bpiwrt" >> /etc/hosts
echo "192.168.2.1     pi.hole" >> /etc/hosts

# Refreshes the certificates:
update-ca-certificates -f

# Sets timezone to "America/Chicago":
rm /etc/localtime
ln -s /usr/share/zoneinfo/America/Chicago /etc/localtime

# Set a placeholder file for chrooting into read-only filesystem:
touch /etc/debian_chroot

# Sets locale to "en_US.UTF-8":
sed -i "s|# en_US.UTF-8 UTF-8|en_US.UTF-8 UTF-8|g" /etc/locale.gen
locale-gen

##############################################################################################
# Place a list of english words in "/usr/share/dict/" for our password generator:
##############################################################################################
wget https://github.com/dobsondev/php-password-generator/raw/master/php-password-generator/adjectives.list -O /usr/share/dict/adjectives.list
wget https://github.com/dobsondev/php-password-generator/raw/master/php-password-generator/animals.list -O /usr/share/dict/animals.list

##############################################################################################
# Download the "mmc" binary and place in "/usr/local/bin":
##############################################################################################
wget https://github.com/frank-w/BPI-R2-4.14/raw/4.14-main/utils/mmc/mmc -O /usr/local/bin/mmc
chmod +x /usr/local/bin/mmc

##############################################################################################
# Get the file we'll need to flash during SD->EMMC copies:
##############################################################################################
wget https://github.com/BPI-SINOVOIP/BPI-files/raw/master/SD/100MB/BPI-R2-EMMC-boot0-DDR1600-0k-0905.img.gz -O /boot/BPI-R2-EMMC-boot0-DDR1600-0k-0905.img.gz

##################################################################################
# Create our custom login message:
##################################################################################
rm /etc/motd
rm /etc/update-motd.d/10-uname
ln -s /var/run/motd /etc/motd

##################################################################################
# Install some new utilities
##################################################################################
apt install -y pciutils usbutils iw wireless-tools net-tools curl unzip debconf-utils tree screen parted device-tree-compiler

##################################################################################
# Install avahi utilities
##################################################################################
apt install -y avahi-daemon 
systemctl enable avahi-daemon

##################################################################################
# Install utility to track internet usage by adapter:
##################################################################################
apt install -y vnstat
systemctl disable vnstat

##################################################################################
# Install Samba
##################################################################################
echo "samba-common samba-common/dhcp boolean true" | debconf-set-selections
apt install -y samba
echo -e "bananapi\nbananapi" | smbpasswd -a pi
# NOTE: Modify the Samba configuration to make sharing USB sticks more automatic
sed -i "1s|^|include = /etc/samba/includes.conf\n\n|" /etc/samba/smb.conf
touch /etc/samba/includes.conf
sed -i "s|/var/run|/run|g" /lib/systemd/system/?mbd.service
systemctl enable smbd
systemctl enable nmbd

##################################################################################
# Install NGINX and PHP 7.3
##################################################################################
apt install -y nginx php7.3-fpm php7.3-cgi php7.3-xml php7.3-sqlite3 php7.3-intl apache2-utils php7.3-mysql php7.3-sqlite3 sqlite3 php7.3-zip openssl php7.3-curl
sed -i "s|display_errors = .*|display_errors = On|g" /etc/php/7.3/fpm/php.ini
rm /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/router /etc/nginx/sites-enabled/default
usermod -aG systemd-journal www-data
systemctl enable php7.3-fpm
systemctl enable nginx
apt-mark hold php7.3-fpm
echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

##################################################################################
# Install and configure miniupnp install
##################################################################################
# NOTE: Install the miniupnp install quietly
echo "miniupnpd miniupnpd/start_daemon boolean true" | debconf-set-selections
echo "miniupnpd miniupnpd/ip6script boolean false" | debconf-set-selections
echo "miniupnpd miniupnpd/listen string br0" | debconf-set-selections
echo "miniupnpd miniupnpd/iface string wan" | debconf-set-selections
apt install -y miniupnpd miniupnpc
# NOTE: Configure the service:
sed -i "s|#ext_ifname=eth1|ext_ifname=wan|g" /etc/miniupnpd/miniupnpd.conf
sed -i "s|#listening_ip=eth0|listening_ip=br0|g" /etc/miniupnpd/miniupnpd.conf
sed -i "s|#secure_mode=|secure_mode=|g" /etc/miniupnpd/miniupnpd.conf
sed -i "s|#http_port=0|http_port=5000|g" /etc/miniupnpd/miniupnpd.conf
sed -i "s|#enable_upnp=no|enable_upnp=yes|g" /etc/miniupnpd/miniupnpd.conf
sed -i "s|#enable_natpmp=yes|enable_natpmp=yes|g" /etc/miniupnpd/miniupnpd.conf
systemctl enable miniupnpd

##################################################################################
# Install minissdpd package
##################################################################################
# NOTE: Set some default settings for minissdpd package:
echo "minissdpd minissdpd/listen string br0" | debconf-set-selections
echo "minissdpd minissdpd/ip6 boolean false" | debconf-set-selections
echo "minissdpd minissdpd/start_daemon boolean true" | debconf-set-selections
# NOTE: Install minissdpd package:
apt install -y minissdpd
systemctl enable minissdpd

##################################################################################
# Install docker and add bin directory on docker partition to system path
##################################################################################
curl -L https://get.docker.com | bash
usermod -aG docker pi
sed -i "s|PATH=\"|PATH=\"/var/lib/docker/bin:|g" /etc/profile

##################################################################################
# Download docker-compose into the /usr/local/bin directory
##################################################################################
wget https://github.com/tsitle/dockercompose-binary_and_dockerimage-aarch64_armv7l_x86_x64/raw/master/binary/docker-compose-linux-armhf-1.27.4.tgz -O /tmp/docker.tgz
pushd /tmp
tar xvzf /tmp/docker.tgz
mv docker-compose-linux-armhf-1.27.4 /usr/local/bin/
ln -sf /usr/local/bin/docker-compose-linux-armhf-1.27.4 /usr/local/bin/docker-compose
popd

##################################################################################
# Install the wireless regulatory table
##################################################################################
apt install -y wireless-regdb crda
git clone https://git.kernel.org/pub/scm/linux/kernel/git/sforshee/wireless-regdb.git/ /opt/wireless-regdb
ln -sf /opt/wireless-regdb/regulatory.db /lib/firmware/
ln -sf /opt/wireless-regdb/regulatory.db.p7s /lib/firmware/

##################################################################################
# Install Transmission-BT program
##################################################################################
mv /etc/transmission-daemon/settings.json /tmp/settings.json
apt install -y transmission-daemon
mv /tmp/settings.json /etc/transmission-daemon/settings.json
chown -R vpn:vpn /etc/transmission-daemon/
chown -R vpn:vpn /var/lib/transmission-daemon/
chmod -R 775 /etc/transmission-daemon/
chmod -R 775 /var/lib/transmission-daemon/
mkdir /home/vpn/{Incomplete,Download}
chown -R vpn:vpn /home/vpn/{Incomplete,Download}
chmod -R 775 /home/vpn/{Incomplete,Download}
systemctl enable transmission-daemon

##################################################################################
# Install TrueCrypt and HD-Idle
##################################################################################
wget https://github.com/stefansundin/truecrypt.deb/releases/download/7.1a-15/truecrypt-cli_7.1a-15_armhf.deb -O /tmp/truecrypt.deb
wget https://github.com/adelolmo/hd-idle/releases/download/v1.12/hd-idle_1.12_armhf.deb -O /tmp/hdidle.deb
mv /etc/default/hd-idle /tmp/
apt install -y /tmp/*.deb
mv /tmp/hd-idle /etc/default/hd-idle
rm /tmp/*.deb

##################################################################################
# Pull ydns's bash-updater repo and modify to pull settings from elsewhere
##################################################################################
git clone https://github.com/ydns/bash-updater /opt/ydns-updater
sed -i "s|^YDNS_LASTIP_FILE|[[ -f /etc/default/ydns-updater ]] \&\& source /etc/default/ydns-updater\nYDNS_LASTIP_FILE|" /opt/ydns-updater/updater.sh
chown www-data:www-data /etc/default/ydns-updater

##################################################################################
# Pull in dependencies to make the SSD1306 front display work:
##################################################################################
apt install -y --no-install-recommends i2c-tools python3-pip python3-pil python3-venv
python3 -m pip install --upgrade pip wheel setuptools virtualenv
git clone https://github.com/frank-w/bpi-r2-ssd1306-display /opt/stats
ln -sf /opt/stats/stats.service /etc/systemd/system/stats.service
systemctl enable stats
mkdir /var/lib/stats
chown pi:pi /var/lib/stats
sudo -u pi -s /opt/bpi-r2-router-builder/misc/build_stats.sh

##################################################################################
# Install PiHole
##################################################################################
curl -L https://install.pi-hole.net | bash /dev/stdin --unattended
# NOTE: Mask "dnsmasq" package so we don't conflict with it!
systemctl stop dnsmasq
systemctl disable dnsmasq
systemctl mask dnsmasq
# NOTE: Configure some things correctly
chown pihole:pihole /var/lib/misc
chown pihole:pihole -R /var/lib/misc/*
chown www-data:www-data -R /var/www/html
chown www-data:www-data -R /var/www/html/*
rm /var/www/html/index.nginx-debian.html
# NOTE: Add pihole group to www-data
usermod -aG pihole www-data
# NOTE: Set default password as "bananapi"
pihole -a -p bananapi
# NOTE: Set default DNS to cloudflare port 5051
sed -i "/PIHOLE_DNS_.*/d" /etc/pihole/setupVars.conf
echo "PIHOLE_DNS_1=127.0.0.1#5335" >> /etc/pihole/setupVars.conf
pihole restartdns
# NOTE: Add site configuration for "pi.hole":
ln -sf /etc/nginx/sites-available/pihole /etc/nginx/sites-enabled/pihole
systemctl restart nginx
# NOTE: Add our custom script to sudoers.d:
echo "www-data ALL=NOPASSWD: /usr/local/sbin/pihole" >> /etc/sudoers.d/pihole

##################################################################################
# Q: Maybe install these packages?
##################################################################################
#apt install -y vlan ipset traceroute nmap conntrack ndisc6 whois iperf3 tcpdump ethtool irqbalance 

##################################################################################
# Install cloudflared binary:
##################################################################################
wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm -O /usr/local/bin/cloudflared
chmod +x /usr/local/bin/cloudflared
useradd -s /usr/sbin/nologin -r -M cloudflared
chown cloudflared:cloudflared /etc/default/cloudflared
chown cloudflared:cloudflared /usr/local/bin/cloudflared
systemctl enable cloudflared
systemctl start cloudflared

##################################################################################
# Install & configure unbound:
##################################################################################
apt install -y unbound
systemctl enable unbound
systemctl start unbound
