#!/bin/bash
cd /home/doug/R2
for ver in 5.6 5.7 5.8 5.9 5.10 5.15; do
	CHECK=n
	! test -d BPI_${ver} && CHECK=y
	[[ "$1" == "-r" ]] && umount BPI_${ver} && rm -rf BPI_${ver}
	mkdir -p BPI_${ver}
	mkdir -p .tmp/${ver}_{upper,work}
	mount -t overlay -o lowerdir=.tmp/BPI-R2-4.14,upperdir=.tmp/${ver}_upper,workdir=.tmp/${ver}_work overlay BPI_${ver}
	if [[ "${CHECK}" == "y" ]]; then
		pushd BPI_${ver}
		git checkout ${ver}-main
		popd
	fi
done
