#!/bin/bash
if [[ "$UID" -ne 0 ]]; then
	sudo $0 $@
	exit
fi
RED='\033[1;31m'
GREEN='\033[1;32m'
BLUE='\033[1;34m'
NC='\033[0m'
mkdir -p ~/R2
cd ~/R2
if [[ "$1" == "-r" ]]; then
	for file in BPI_*; do echo -e "${GREEN}INFO:${NC} Unmounting ${file}..."; umount ${file}; done
	for file in BPI_*; do echo -e "${GREEN}INFO:${NC} Removing ${file}..."; rm -rf ${file}; done
	for file in .tmp/*; do echo -e "${GREEN}INFO:${NC} Removing ${file}..."; rm -rf ${file}; done
	echo -e "${GREEN}INFO:${NC} Updated local BPI-R2-4.14 repository..."
	cd .BPI-R2-4.14
	git pull
	cd ..
fi
for ver in 5.6 5.7 5.8 5.9 5.10 5.15; do
	echo -e "${GREEN}INFO:${NC} Mounting branch ${BLUE}${ver}-main${NC}...."
	test -d .tmp/${ver}_upper && CHECK=N || CHECK=Y
	mkdir -p BPI_${ver}
	mkdir -p .tmp/${ver}_{upper,work}
	chown doug:doug -R BPI_${ver}
	chown doug:doug -R .tmp/${ver}_{upper,work}
	mount -t overlay -o lowerdir=.BPI-R2-4.14,upperdir=.tmp/${ver}_upper,workdir=.tmp/${ver}_work overlay BPI_${ver}
	if [[ "$CHECK" == "Y" ]]; then
		echo -e "${GREEN}INFO:${NC} Checking out branch ${BLUE}${ver}-main${NC}...."
		cd BPI_${ver}
		sudo -u doug git checkout ${ver}-main
		sudo -u doug ./build.sh importconfig
		cd ..
	fi
done
cp ~/GitHub/bpiwrt-builder/.kernel_config ~/R2/BPI-R2-4.14/
