#!/bin/bash
if [[ "$UID" -ne 0 ]]; then
	sudo $0 $@
	exit
fi
RED='\033[1;31m'
GREEN='\033[1;32m'
BLUE='\033[1;34m'
NC='\033[0m'

if [[ -z "$1" || "$1" == "BOOT" ]]; then
	DEV=$(sudo blkid | grep "BPI-BOOT" | cut -d":" -f 1)
	if [[ -z "${DEV}" ]]; then
		echo "${RED}ERROR:${NC} SD Card not detected with partition 1 label of ${BLUE}BPI-BOOT${NC}!"
		exit 1
	fi
	MOUNT=$(mount | grep ${DEV} | cut -d" " -f 3)
	[[ -z "${MOUNT}" ]] && mkdir /media/BPI-BOOT && mount ${DEV} /media/BPI-BOOT && MOUNT=/media/BPI-BOOT
	cp -avr SD/BPI-BOOT/* ${MOUNT}/
fi
if [[ -z "$1" || "$1" == "ROOT" ]]; then
	DEV=$(sudo blkid | grep "BPI-ROOT" | cut -d":" -f 1)
	if [[ -z "${DEV}" ]]; then
		echo "${RED}ERROR:${NC} SD Card not detected with partition 1 label of ${BLUE}BPI-ROOT${NC}!"
		exit 1
	fi
	MOUNT=$(mount | grep ${DEV} | cut -d" " -f 3)
	[[ -z "${MOUNT}" ]] && mkdir /media/BPI-ROOT && mount ${DEV} /media/BPI-ROOT && MOUNT=/media/BPI-ROOT
	cp -avr SD/BPI-ROOT/* ${MOUNT}/

	# Copy MediaTek MT7615 firmware:
	cp -avr root/* ${MOUNT}/
fi
