#!/bin/bash

# Use Receive Packet Steering (RPS) to steer incoming data from "wan" to CPUs 2 and 3:
[[ "${IFACE}" == "wan" ]] && echo 6 > /sys/class/net/${IFACE}/queues/rx-0/rps_cpus

# Use Receive Packet Steering (RPS) to steer incoming data from "br0" to CPUs 4:
[[ "${IFACE}" == "br0" ]] && echo 8 > /sys/class/net/${IFACE}/queues/rx-0/rps_cpus

# Exit with a zero error code:
exit 0
