#!/bin/bash
[[ -f /etc/default/firewall ]] && source /etc/default/firewall
if [[ "$IFACE" == "br0" ]]; then
	[[ "${redirect_dns:-"Y"}" == "N" ]] && exit 0
	PIHOLE=$(ifconfig br0 | grep 'inet ' | awk '{print $2}')
	iptables -t nat -A PREROUTING -p udp ! --source ${PIHOLE} ! --destination ${PIHOLE} --dport 53 -j DNAT --to ${PIHOLE}
	iptables -t nat -A PREROUTING -p tcp ! --source ${PIHOLE} ! --destination ${PIHOLE} --dport 53 -j DNAT --to ${PIHOLE}
elif [[ "$IFACE" == "wan" ]]; then
	/opt/bpi-r2-router-builder/router-helper.sh dns use_isp
fi
