#!/bin/bash
if [[ "$IFACE" == "br0" ]]; then
	[[ -f /etc/default/firewall ]] && source /etc/default/firewall
	[[ "${redirect_dns:-"Y"}" == "N" ]] && exit 0
	PIHOLE=$(ifconfig br0 | grep 'inet ' | awk '{print $2}')
	iptables -t nat -A PREROUTING -p udp ! --source ${PIHOLE} ! --destination ${PIHOLE} --dport 53 -j DNAT --to ${PIHOLE}
	iptables -t nat -A PREROUTING -p tcp ! --source ${PIHOLE} ! --destination ${PIHOLE} --dport 53 -j DNAT --to ${PIHOLE}
fi
