version: "2"
services:
  cups:
    image: tigerj/cups-airprint:latest
    container_name: cups
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /var/lib/docker/data/cups/config:/config
      - /var/lib/docker/data/cups/services:/services
    devices:
      - /dev/bus:/dev/bus
      - /dev/usb:/dev/usb
    environment:
      - CUPSADMIN=admin
      - CUPSPASSWORD=password
