<?php
# source: https://www.arubanetworks.com/techdocs/InstantWenger_Mobile/Advanced/Content/Instant%20User%20Guide%20-%20volumes/Country_Codes_List.htm
$countries = array(
	'US' => 'United States',
	'CA' => 'Canada',
	'JP' => 'Japan',
	'DE' => 'Germany',
	'NL' => 'Netherlands',
	'IT' => 'Italy',
	'PT' => 'Portugal',
	'LU' => 'Luxembourg',
	'NO' => 'Norway',
	'FI' => 'Finland',
	'DK' => 'Denmark',
	'CH' => 'Switzerland',
	'CZ' => 'Czech Republic',
	'ES' => 'Spain',
	'GB' => 'United Kingdom',
	'KR' => 'Republic of Korea (South Korea)',
	'CN' => 'China',
	'FR' => 'France',
	'HK' => 'Hong Kong',
	'SG' => 'Singapore',
	'TW' => 'Taiwan',
	'BR' => 'Brazil',
	'IL' => 'Israel',
	'SA' => 'Saudi Arabia',
	'LB' => 'Lebanon',
	'AE' => 'United Arab Emirates',
	'ZA' => 'South Africa',
	'AR' => 'Argentina',
	'AU' => 'Australia',
	'AT' => 'Austria',
	'BO' => 'Bolivia',
	'CL' => 'Chile',
	'GR' => 'Greece',
	'IS' => 'Iceland',
	'IN' => 'India',
	'IE' => 'Ireland',
	'KW' => 'Kuwait',
	'LI' => 'Liechtenstein',
	'LT' => 'Lithuania',
	'MX' => 'Mexico',
	'MA' => 'Morocco',
	'NZ' => 'New Zealand',
	'PL' => 'Poland',
	'PR' => 'Puerto Rico',
	'SK' => 'Slovak Republic',
	'SI' => 'Slovenia',
	'TH' => 'Thailand',
	'UY' => 'Uruguay',
	'PA' => 'Panama',
	'RU' => 'Russia',
	'EG' => 'Egypt',
	'TT' => 'Trinidad and Tobago',
	'TR' => 'Turkey',
	'CR' => 'Costa Rica',
	'EC' => 'Ecuador',
	'HN' => 'Honduras',
	'KE' => 'Kenya',
	'UA' => 'Ukraine',
	'VN' => 'Vietnam',
	'BG' => 'Bulgaria',
	'CY' => 'Cyprus',
	'EE' => 'Estonia',
	'MU' => 'Mauritius',
	'RO' => 'Romania',
	'CS' => 'Serbia and Montenegro',
	'ID' => 'Indonesia',
	'PE' => 'Peru',
	'VE' => 'Venezuela',
	'JM' => 'Jamaica',
	'BH' => 'Bahrain',
	'OM' => 'Oman',
	'JO' => 'Jordan',
	'BM' => 'Bermuda',
	'CO' => 'Colombia',
	'DO' => 'Dominican Republic',
	'GT' => 'Guatemala',
	'PH' => 'Philippines',
	'LK' => 'Sri Lanka',
	'SV' => 'El Salvador',
	'TN' => 'Tunisia',
	'PK' => 'Islamic Republic of Pakistan',
	'QA' => 'Qatar',
	'DZ' => 'Algeria'
);
$empty = array();
foreach (explode("\n", trim(@shell_exec('cat /opt/wireless-regdb/db.txt | grep -i "country " | cut -d" " -f 2 | cut -d":" -f 1'))) as $country)
{
	if (isset($countries[$country]))
		$empty[$country] = $countries[$country];
}
$countries = $empty;
unset($empty);
	