#!/bin/bash

# Tools needed for compiling the kernel on the BPI-R2:
apt install -y gcc-arm-linux-gnueabihf libc6-armhf-cross u-boot-tools bc make gcc libc6-dev libncurses5-dev libssl-dev bison flex ccache

# APT Packages for the wheel2deb package:
apt install -y python3-apt apt-file dpkg-dev fakeroot build-essential devscripts debhelper python3-smbus
pip install --upgrade pip setuptools wheel wheel2deb
