#!/bin/bash
UPNP_URL=
UPNP_IP=($(ifconfig br0 | grep " inet "))
UPNP_PORT=$(netstat -peanut | grep miniupnpd | grep ":::" | awk '{print $4}' | cut -d: -f 4)
[[ ! -z "${UPNP_PORT}" && "${UPNP_PORT}" -gt 0 ]] && UPNP_URL="-u http://${UPNP_IP[1]}:${UPNP_PORT}/ctl/IPConn"
/usr/bin/upnpc ${UPNP_URL} $@
