#!/bin/bash
UPNP_URL=
UPNP_IP=($(ifconfig br0 | grep " inet "))
UPNP_PORT=$(cat /etc/miniupnpd/miniupnpd.conf | grep -e "^http_port=" | cut -d"=" -f 2)
[[ ! -z "${UPNP_PORT}" && "${UPNP_PORT}" -gt 0 ]] && UPNP_URL="-u http://${UPNP_IP[1]}:${UPNP_PORT}/ctl/IPConn"
/usr/bin/upnpc ${UPNP_URL} $@
