#!/bin/bash
# Docker, for whatever reason, breaks the functionality of this router when using Docker containers.
# This script duplicates the FORWARD rules into the DOCKER-USER so that the router is still usable.

function docker-rules()
{
	echo "*filter"
	echo "-N DOCKER-USER"
	cat /etc/network/iptables.rules | grep "\-A FORWARD" | sed "s/-A FORWARD/-I DOCKER-USER/g"
	echo "COMMIT"
}

docker-rules | iptables-restore -n
exit 0

