#!/bin/bash

REBOOT=false
PCI=$(lspci | grep MEDIATEK | grep 7615 | cut -d" " -f 1)
if [[ ! -z "${PCI}" ]]; then
	cd /sys/class/net
	IFACES=($(ls -l | grep "${PCI}" | awk '{print $9}' | grep -v "^mt_"))
	for IFACE in ${IFACES[@]}; do
		# Change MAC address:
		MAC=$(ifconfig ${IFACE} | grep ether | awk '{print $2}')
		NEW=mt_24g
		[[ "${IFACE}" == "rename"* ]] && NEW=mt_50g
		sed -i "/${MAC}/d" /etc/udev/rules.d/70-persistent-net.rules
		echo "SUBSYSTEM==\"net\", DRIVERS==\"?*\", ATTR{address}==\"${MAC}\", NAME=\"${NEW}\"" >> /etc/udev/rules.d/70-persistent-net.rules
		REBOOT=true
	done
fi
[[ "$REBOOT" == "true" ]] && reboot now
exit 0
