#!/bin/bash
### BEGIN INIT INFO
# Provides:       wifi
# Required-Start: $network $remote_fs $syslog
# Required-Stop:  $network $remote_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    Load MediaTek MT6625L firmware
### END INIT INFO

#==================================================================================
# Don't exit on error status and load router configuration:
#==================================================================================
set +e
[[ -f /etc/default/router-settings ]] && source /etc/default/router-settings

#==================================================================================
# If wifidev doesn't exist, sleep for 120 seconds before proceeding:
#==================================================================================
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/dev/null
NAME=wifi
DESC="Load MediaTek MT6625L firmware wifi & BT"

if [[ ! -e /dev/wmtWifi ]]; then
	echo "wifidev does not exist...create it..."
	if [[ -x /usr/bin/wmt_loader ]]; then
		/usr/bin/wmt_loader &> /var/log/wmtloader.log
		sleep 3
	else
		echo "Error, unable to find wmt_loader"
	fi

	# Check FILE exists and is character special
	if  [[ -c /dev/stpwmt ]]; then
		/usr/bin/stp_uart_launcher -p /etc/firmware &> /var/log/stp_launcher.log &
		sleep 5
	else
		echo "Error, device no created, /dev/stpwmt"
	fi
fi

#==================================================================================
# Load wifi module if found on the system:
#==================================================================================
echo "loading wifi driver module"
modprobe wlan_gen2

#==================================================================================
# Check FILE exists and is character special
#==================================================================================
if  [[ -c /dev/wmtWifi ]];
then
	systemctl is-active hostapd@ap0 >& /dev/null && systemctl stop hostapd@ap0
	sleep 1
	if [[ -n $(ip a|grep ap0) ]]; then
		echo "ap0 exists, reset it";
		echo 0 | tee /var/run/wmtWifi > /dev/wmtWifi
		sleep 5
	fi
	echo ${onboard_wifi:="A"} | tee /var/run/wmtWifi > /dev/wmtWifi
	sleep 2
else
	echo "Error, wifi device no created, /dev/wmtWifi"
fi

#==================================================================================
# Load bluetooth module, then configure bluetooth interface correctly:
#==================================================================================
echo "loading bt driver module"
modprobe stp_chrdev_bt
hciconfig hci0 lm master
sleep 1
hciconfig hci0 up
sleep 1
hciconfig hci0 class ff0104
