#!/bin/bash

# Load router settings:
[[ -f /etc/default/router-settings ]] && source /etc/default/router-settings

# Are we dealing with the "br0" interface? 
if [[ "$IFACE" == "br0" ]]; then
	for HANDLE in $(nft -a list chain inet firewall prerouting_lan | grep " dport 53 " | awk '{print $NF}'); do 
		nft delete rule inet firewall prerouting_lan handle ${HANDLE}
	done
fi
exit 0
